### ISSUE TITLE
click with primary mouse btn in explorer view

### ISSUE THREAD

**Issue by bbak** [fabiospampinato/vscode-projects-plus#11]
This click used to open the Project clicked.

In 1.1.13, it doesn't anymore. I don't know, if that was introduced in 1.1.13 or .12.

Using the context menu (secondary mouse btn) along with selecting "Open..." still works. This may be related to the fact, that I'm lefthanded and therefore switched my mouse buttons. :-)

**Comment by fabiospampinato** [comment]
This should be fixed in v1.13.1. I accidentally broke it with the previous update.

Thanks for reporting the issue.
