### ISSUE TITLE
Support cross platform path definitions with ($HOME)

### ISSUE THREAD

**Issue by duranivan** [fabiospampinato/vscode-projects-plus#12]
As you mention in the **Hits** section of the documentation, I could sync my projects by making `projects.configPath` point to a location in my Dropbox. However as I see it now, the path has to be specific to the machine, such as `/User/Name/Dropbox/vscode_projects.json`. But if my two machines have different user names, then I have a problem if I am syncing my user `settings.json` as well. But even if I am not syncing my `settings.json`, the projects paths in `vscode_projects.json` should support a cross platform definition for example by using `$home`, otherwise I will encounter the same problem.

Is it possible at the moment to define the paths with something like `$home`? The project manager extension did this recently, but I like your extension much better, so I am planning to switch.

Thanks in advance!

**Comment by fabiospampinato** [comment]
Thanks for the suggestion. I've implemented this in v1.14.0.

Instead of `$home` it uses `~` though, which seems more logical to me.

Let me know if you find some issues!

**Comment by duranivan** [comment]
Great, will try it out. Thanks a lot!
