### ISSUE TITLE
Consider adding setting "projects.statusbarColor"

### ISSUE THREAD

**Issue by msageryd** [fabiospampinato/vscode-projects-plus#13]
Awesome work Fabio!
I've switched from **Project Manager** to **Project+** and I'm very happy.

Please consider adding a setting for the color of the text on the statusbar.

Via your **Commands** extension and **Todo+** I have a Todo-button beside the project name on the status bar. I'd like to match the colors of those to differentiate against other statusbar info.

**Comment by fabiospampinato** [comment]
I like the idea, I'll implement this as soon as I get some free time.

**Comment by fabiospampinato** [comment]
Fixed in v1.15.0.
