### ISSUE TITLE
Is sortProjects taken into consideration?

### ISSUE THREAD

**Issue by bartosz-antosik** [fabiospampinato/vscode-projects-plus#15]
Hi! I have `projects.sortProjects` set to `false` but it somehow still does sort the projects on the list alphabetically:

Select:

![image](https://user-images.githubusercontent.com/20492548/33989419-b8551366-e0c7-11e7-8289-3fd2e0c1a2dc.png)

`vscode_projects.json`:

![image](https://user-images.githubusercontent.com/20492548/33989458-e55b7fd0-e0c7-11e7-9406-bdc10773c442.png)

All I have in User settings is:

    (...)
    "projects.viewAllEnabled": false,
    "projects.sortProjects": false

Maybe I am missing something?

**Comment by fabiospampinato** [comment]
@bartosz-antosik This looks like a bug, thanks for reporting it.

I'll work on it as soon as I have some free time.

**Comment by fabiospampinato** [comment]
Fixed in v1.14.1.
