### ISSUE TITLE
Create groups when using projects.refreshRoots

### ISSUE THREAD

**Issue by mikeburgh** [fabiospampinato/vscode-projects-plus#16]
Great extension! The automatic discovery with projects.refreshRoots is very handy.

Any thoughts about having it create groups from parent folders for the projects it finds ? 

For example, with the following folders:

- Group Folder 1
-- project folder 1
-- project folder 2

- Group Folder 2
-- project folder 1
-- project folder 2

It would be nice if the projects were grouped up based on their containing folder.. So you end up with projects and grouping, that matches the folder structure.

If that makes sense ?

**Comment by fabiospampinato** [comment]
Thank you :)

I think it would make sense for some people, but it wouldn't for many others. Unless you continually keep creating many new projects I think it would be easier just to edit the configuration manually and organizing it however you like 🤔

**Comment by mikeburgh** [comment]
Yeah, I think you are right. As I am getting more use to VsCode, typing the project name is faster anyway than browsing groups and selecting. If my usage changes I will look at sending you a PR with the change, but for now I think this can be closed.

**Comment by fabiospampinato** [comment]
Actually even if you use groups you can just simply type a project name to find it. I use groups myself and they are quite good for organizing your projects, they are the very exact reason this extension even exists.

**Comment by mikeburgh** [comment]
Agreed, and I thought originally I would need everything grouped. The more I use it however I find myself just typing the name of what I am looking for.. I manually grouped some projects, but now finding i don't notice that so much. That may change when I have to go and browse for something specific.
