### ISSUE TITLE
command 'projects.open' not found

### ISSUE THREAD

**Issue by duranivan** [fabiospampinato/vscode-projects-plus#19]
It looks like the extension is broken in the last update of VS Code insiders (still fine in the stable release). None of the commands are working, `projects.open`, `projects.save`, etc., even cannot uninstall to try to reinstall the extension again...

(Version 1.22.0-insider, MacOS High Sierra)

Thanks in advance,

**Comment by aboukirev** [comment]
Already discussing it in https://github.com/fabiospampinato/vscode-projects-plus/issues/10
See my workaround there (provide a value for projects.configPath in user settings).  Might help in the meantime.

**Comment by duranivan** [comment]
Problem solved in latest nightly build. I'm closing this...
