### ISSUE TITLE
Switching Projects via Mouse-Click in Explorer View doesn't work anymore

### ISSUE THREAD

**Issue by bbak** [fabiospampinato/vscode-projects-plus#20]
...since today's update.

Using the context menu's "open" command in the Explorer View still works as expected.

**Comment by fabiospampinato** [comment]
@bbak fixed in v1.16.2. 

It looks like the options in the context menu were broken too, especially when using a low value for `projects.viewsRefreshInterval`. Now the explorer view will refresh only when necessary, it should feel snappier and cause no extra lags to VSC.
