### ISSUE TITLE
Use Activity Bar View

### ISSUE THREAD

**Issue by wiecznyPoszukiwacz** [fabiospampinato/vscode-projects-plus#21]
Thanks for great extension!

As VSCode now supports Contributions to the Activity Bar (https://code.visualstudio.com/updates/v1_23#_contributions-to-the-activity-bar) it would be great to see project in separate view instead of panel in file explorer.

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, that would surely be a nice addition.

I'm adding this to my todo list, it may take a few days/weeks for me to find the time required for implementing this though.

**Comment by fabiospampinato** [comment]
Implemented in v1.17.0.

The view contributed to the explorer view is still supported, but disabled by default, in case somebody likes it there better.

**Comment by wiecznyPoszukiwacz** [comment]
Thank you for such a great job!
