### ISSUE TITLE
GitTower bookmarks setting

### ISSUE THREAD

**Issue by colorful-tones** [fabiospampinato/vscode-projects-plus#25]
Git Tower has a great Beta for its v3 out. I've been using daily for a few months. 

I just installed this extension and ran `Projects: Refresh` and was excited to see it pull in my Git Tower projects. However, I then reorganized them in Tower 3 (again Beta), ran `Projects: Refresh` and it didn't update. 😩

So, I then went down the 🕳🐇 <-- Rabbit hole

I found where this extension sets the [`const BOOKMARKS_PATH`](https://github.com/fabiospampinato/vscode-projects-plus/blob/master/src/fetchers/projects/git_tower.ts#L13)

It would be cool to have an override for this `BOOKMARKS_PATH` please? Because Tower 3 Beta has a different location for its `bookmarks-v2.plist` which for me: `/Library/Application\ Support/com.fournova.Tower3/bookmarks-v2.plist`

Thanks for the great extension!

**Comment by colorful-tones** [comment]
For now, I just copied over my `bookmarks-v2.plist` in Tower 3 and replaced it in Tower 2. I hope it doesn't corrupt the installation though of Tower 2, but I don't really use it any more.

**Comment by fabiospampinato** [comment]
Oh yeah I'm definitely going to add support for this. I didn't even know there was a v3 of Git Tower, glad to hear it is still being developed.

**Comment by colorful-tones** [comment]
Tower 3.0 has officially launched: https://www.git-tower.com/blog/the-new-tower-has-launched-2018/

Beta --> official release was seamless, and still has the: `/Library/Application\ Support/com.fournova.Tower3/bookmarks-v2.plist`

**Comment by fabiospampinato** [comment]
Great. I'll probably add support for Tower v3 sometime next week, currently I'm on vacation.

**Comment by fabiospampinato** [comment]
Fixed in v.1.18.0.

Now the most recently updated of the two will be used, so that one can have v3 installed but still using v2's configuration if that's the most updated.

Ps. my god, how ugly is the new app icon!
