### ISSUE TITLE
Icons in views are not shown

### ISSUE THREAD

**Issue by yuriizinets** [fabiospampinato/vscode-projects-plus#26]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/17050536/41563031-b71385c2-734e-11e8-9cbf-5dddf89e5082.png">

VSCode version: 1.24.1
OS: MacOS 10.13.5

**Comment by fabiospampinato** [comment]
I've opened an upstream issue about this https://github.com/Microsoft/vscode/issues/32956.

At the moment icons are only rendered in the quick pick.

**Comment by yzinets** [comment]
Oh. Thanks. Is it any chance that this could be provided?

**Comment by fabiospampinato** [comment]
I don't know, the issue is almost 1 year old so they clearly aren't that interested in implementing it.

Maybe you should add a message to that thread and ask for updates.

**Comment by hacknug** [comment]
Issue was closed upstream. Any chance this could be revisited to add icons at least for groups?

Something else that might improve readability would be turning _Check Dirty_ and _Check Paths_ into an icon placed before the project name and moving _Show Ahead Behind_ to another element like the path next to a file name in Search or the branch info in GitLens' Repositories.

**Comment by fabiospampinato** [comment]
> Issue was closed upstream. Any chance this could be revisited to add icons at least for groups?

PRs are welcome 👍 

> turning Check Dirty and Check Paths into an icon

AFAIK only one icon at a time can be displayed.

> moving Show Ahead Behind to another element

That would make the list quite a lot longer potentially, I'm not convinced this is a good idea for us 🤔

**Comment by hacknug** [comment]
> > turning Check Dirty and Check Paths into an icon
> 
> AFAIK only one icon at a time can be displayed.

Project can't be dirty if folder path doesn't exist so there would only be three diff states: default (aka exists and clean), dirty or missing. No?


> > moving Show Ahead Behind to another element
> 
> That would make the list quite a lot longer potentially, I'm not convinced this is a good idea for us 🤔

I meant changing the ASCII things highlighted on the first picture to something more like the second picture. It's just a way to give it a little more hierarchy and clearly differentiate project names from other info.

<img width="316" alt="Captura de pantalla 2019-10-03 a las 18 50 06" src="https://user-images.githubusercontent.com/1107521/66147394-0d16b280-e60f-11e9-8fc6-16f6c33bcf04.png">
<img width="391" alt="Captura de pantalla 2019-10-03 a las 18 49 42" src="https://user-images.githubusercontent.com/1107521/66147400-0f790c80-e60f-11e9-9db8-08c0a71b08dd.png">

If the first change (icons) could be implemented, I'd move ahead/behind to the right side, where that _M_ is on my screenshot. I think this would help make it more scannable.

**Comment by fabiospampinato** [comment]
> Project can't be dirty if folder path doesn't exist so there would only be three diff states: default (aka exists and clean), dirty or missing. No?

Yeah but are you proposing to substitute the project icon if it's not in the default state then? I'm not sure I'd want that.

> I meant changing the ASCII things highlighted on the first picture to something more like the second picture. It's just a way to give it a little more hierarchy and clearly differentiate project names from other info.

I see, I thought you were talking about putting those in another line. PR welcome for this too 👍

**Comment by hacknug** [comment]
I have this last thing (moving ASCII and behind/ahead) working but there's an issue with it.

The exported class for `TreeItem` (from `vscode/vscode.d.ts`) doesn't include the definition for `description` which is what's needed to move it there. Property is documented [here](https://code.visualstudio.com/api/references/vscode-api#TreeItem).

To prevent TypeScript from complaining about it and breaking the build, I've used `this['description']` instead of `this.description`. This fixes it but I'm pretty sure there's another way around it (first type contributing to a TS project).

This is how things would look like after the changes:
<img width="314" alt="Captura de pantalla 2019-10-04 a las 13 48 51" src="https://user-images.githubusercontent.com/1107521/66205480-caf07e00-e6ad-11e9-9462-2f0a5a37f085.png">

I've also looked into moving the ahead/behind part to the right but it seems [there's not a public API for that yet](https://stackoverflow.com/questions/54504718/custom-view-decorations-in-vscode-extension). Not sure it's worth the trouble right now unless there's something I'm not aware of regarding this.

**Comment by fabiospampinato** [comment]
> This fixes it but I'm pretty sure there's another way around it (first type contributing to a TS project).

Yeah you have to bump the "vscode" field in `package.json` and run `npm i` again. I don't know what version of vscode introduced support for that though.

> This is how things would look like after the changes:

It looks great 👍 

> unless there's something I'm not aware of regarding this.

I think it may actually look better on the left side 🤔 And if there's no API for moving that to the right side than there isn't anything we can do about it.

**Comment by hacknug** [comment]
`vscode` [was deprecated a couple months ago](https://www.npmjs.com/package/vscode). I've tried following [the migration guide](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode) but I'm not sure I understand the whole thing (mostly the test script part as I have no idea how it's set up right now and what would/should change). Could you help you out with this?

**Comment by fabiospampinato** [comment]
Sorry that was ambiguous, I mean [this](https://github.com/fabiospampinato/vscode-projects-plus/blob/master/package.json/#L22-L23) `vscode` property, which governs which TS declaration file gets downloaded.

Right now there are no tests at all, I don't think you'll have to add any.
