### ISSUE TITLE
Clicking on group destroy my config

### ISSUE THREAD

**Issue by SassNinja** [fabiospampinato/vscode-projects-plus#28]
I've several groups with projects so my config (`vscode_projects.json`) looks like

```json
{
  "groups": [
    {
      "name": "foo",
      "projects": []
    },
    {
      "name": "bar",
      "projects": []
    }
  ]
}
```

When I execute `Project: Open` via the command palette I see all my groups and projects and can click on a single project without problems.

But when I click on the group name it destroys my config!
Precisely it appends `"group": "[groupname]"` so I end up with such a config

```json
{
  "groups": [
    {
      "name": "foo",
      "projects": []
    },
    {
      "name": "bar",
      "projects": []
    }
  ],
  "group": "loremipsum"
}
```

Afterwards, when I try to switch project, the window only shows the projects of the previously clicked group and nothing else. To fix it I have to manually fix the config.

I'm using
- macOS High Sierra
- VSCode v1.26.0

**Comment by fabiospampinato** [comment]
That's actually a feature:

> **Group switching**: if you have many groups, you can choose to view only projects belonging to a single one of them. Switching between groups is super easy.

You can switch back to the special "All Groups" group by running the command named `Projects: Switch Group` or by hitting `cmd+alt+shift+x`
