### ISSUE TITLE
Setting to open in new Window by default.

### ISSUE THREAD

**Issue by mhubig** [fabiospampinato/vscode-projects-plus#29]
It would be nice if there where a settings flag to oben a project in a new window instead of opening within the current window when double clicking on a project.

**Comment by fabiospampinato** [comment]
VSC doesn't provide any API for listening to double-click events.

But I could add a setting for opening projects in a new window by default with a single click. I'm talking about the activity bar view. Would that be enough?

**Comment by mhubig** [comment]
Yes shure, this would totally solve my use case!.Thanks for the quick reply!

**Comment by fabiospampinato** [comment]
Implemented in v.1.19, just add `"projects.viewOpenInNewWindow": true` to your settings.

**Comment by mhubig** [comment]
Nice! Thank you very much!!

**Comment by joaoreynolds** [comment]
This doesn't seem to work when using the shortcut (Command+Alt+P) - only if I click on the project in the projects tab. Is that something that can be changed?

**Comment by fabiospampinato** [comment]
@joaoreynolds Can you open a separate bug about that? But I can't reproduce it. Maybe you could set `projects.viewOpenInNewWindow = true`
