### ISSUE TITLE
Create groups automatically based on nesting from `refreshRoots`

### ISSUE THREAD

**Issue by alber70g** [fabiospampinato/vscode-projects-plus#30]
Basically the title. I have my own and corporate projects on one machine, and I clone projects in the directory of the author/owner. So it'd be nice if Projects+ would automatically detect that.

Example directory structure
```
/projects
  /prive
    /alber70g
      /reduxStateMixin
        /.git
      /next-project
        /.git
    /fabiospampinato
      /vscode-projects-plus
        /.git
      /..
        /.git
  /company
    /team-1
      /project-1
        /.git
    /team-2
      /project-x
        /.git
```

**Comment by jward-2ndwatch** [comment]
I would love to see a feature like this also. I was thinking that maybe the refresh roots setting could allow me to specify the which group to place them in. Something along the lines of:

```json
"projects.refreshRoots": [{"path": "/path/to/projects", "group": "group-for-this-root"},...]
```

**Comment by fabiospampinato** [comment]
Sorry I forgot to reply to this.

Maybe we could add an option for inferring groups from paths. If enabled, by default we will map each refresh root to the last portion of its path.

I'd be happy to consider a PR that adds support for this.

**Comment by pksunkara** [comment]
Sent a PR for this.
