### ISSUE TITLE
$HOME/~ doesn't work for some settings

### ISSUE THREAD

**Issue by edwardgalligan** [fabiospampinato/vscode-projects-plus#32]
I've tried setting `"projects.refreshRoots"` to `~/some/path` in the main vscode `settings.json`, but I get a *"Directory does not exist"* error notification when trying to refresh.

#12 seems to indicate that this should work for a tilde. Is this just for certain settings? Or for paths in the projects config?

**Comment by fabiospampinato** [comment]
Fixed in v1.21.0.

You can now write paths like that also for:

`projects.configPath`
`projects.refreshIgnoreFolders`
`projects.refreshRoots`
