### ISSUE TITLE
Crashes the Extension Host in current Insiders Version

### ISSUE THREAD

**Issue by alexandertrefz** [fabiospampinato/vscode-projects-plus#34]
Enabling Projects+ on the current insiders reliably crashes the Extension Host for me after a few seconds, event with all other extensions disabled.

**Comment by fabiospampinato** [comment]
It sounds like a bug that should be reported to VSC itself, no? 🤔

**Comment by alexandertrefz** [comment]
Potentially - but yours is the only extension to break of my 20ish (at least indicating that the issue is somewhat specific to the plugin) - and at least AFAICT nobody has opened a new issue on VSC for this kinda problem (there are older, closed versions of this one) and  if I were to report to VSC they would probably say, give us some info about the extension etc - which you are in a better position to provide - i would imagine that you might open an issue with VSC - if it indeed is their issue, but only you can tell that, and i would have imagined that you also would like to know about your extensions breaking before it hits VSC Stable.

**Comment by fabiospampinato** [comment]
Well I also didn't push any updates so whatever caused the extension to crash wasn't caused by me. I've taken a quick look at this and I've no idea why exactly it makes the extension host crash, whatever it is it's something on their end, I've just opened the issue here: https://github.com/Microsoft/vscode/issues/65335

**Comment by fabiospampinato** [comment]
It looks like I'll have to switch from using Chokidar to using the provided file watching APIs, I'll probably do that by the end of this week or early next week.
