### ISSUE TITLE
viewOpenInNewWindow does not work when opening with shortcut

### ISSUE THREAD

**Issue by joaoreynolds** [fabiospampinato/vscode-projects-plus#36]
I have in my settings:
`"projects.viewOpenInNewWindow": true`

When I open when using the projects tab UI, it opens in a new window, but when I open using `Cmd+Alt+P` it opens in the same window. But if I open with `Cmd+Alt+Shift+P` it DOES open in a new window, but I would expect the `viewOpenInNewWindow` setting to specify the default behavior.

Perhaps, by design, you want to maintain the different between `Cmd+Alt+P` and `Cmd+Alt+Shift+P`, and I can live with that - it just took a while for me to realize I had to use the shift too.

Info about my system:
Using Mac: High Sierra
VS Code version: 1.31.1
Projects+ version: 1.21.1

I hope that's helpful.

**Comment by fabiospampinato** [comment]
> but I would expect the `viewOpenInNewWindow` setting to specify the default behavior.

That's explicitly about the `view`. 

If you want this as the "default" you have to change the command that's run for those shortcuts.

> it just took a while for me to realize I had to use the shift too.

Did you not read the readme or was it unclear? 🤔
