### ISSUE TITLE
Open project in a new window only if none have been opened yet

### ISSUE THREAD

**Issue by jjavierdguezas** [fabiospampinato/vscode-projects-plus#37]
Hi, thanks for this amazing extension
I have set to open a new window by default. If I open `vscode` (not a folder, not a file, just the IDE) and I click in my project list I do not want another window to open. Could that check be included?

**Comment by fabiospampinato** [comment]
Sounds reasonable, PR welcome 👍

**Comment by jjavierdguezas** [comment]
@fabiospampinato I made a pull request 👉 #38

**Comment by fabiospampinato** [comment]
@jjavierdguezas Thanks, I'll get it merged as soon as I can (maybe later today).
