### ISSUE TITLE
Group name 'Config' breaks loading of projects

### ISSUE THREAD

**Issue by LeanderD** [fabiospampinato/vscode-projects-plus#43]
When a group has the name `Config` I can only see the project(s) from that group. All my other projects are "gone". They are still in the vscode_projects.json, but will not show up in the sidebar panel or in the quick open panel.
It does not happen with `config`, `ConfiG` etc.

When I rename that group all my projects show up again.

**Comment by fabiospampinato** [comment]
Maybe "Config" is the currently active group? ("Projects: Switch Group")

**Comment by LeanderD** [comment]
Ahh yes! You are right.
No idea how that happened (since I've never used that feature on purpose), but I think it must've been the active group.

I see that 'All Groups' is active now and when I change the group name back to `Config` everything is still visible.

So somehow `Config` was set as the active group earlier.
Thanks for your help!
