### ISSUE TITLE
Update the icons

### ISSUE THREAD

**Issue by johnletey** [fabiospampinato/vscode-projects-plus#44]
With the new vscode icons being released soon 🎉 (https://github.com/microsoft/vscode/issues/8017) ... your extension sidebar icon looks weird:

<img width="41" alt="Screen Shot 2019-07-09 at 8 38 56 AM" src="https://user-images.githubusercontent.com/30328854/60862098-42388200-a225-11e9-870b-084f57a42cc0.png">

> Picture taken in Visual Studio Code - Insiders (which already has the new icons)

I already have an updated icon in mind that looks more like the other sidebar icons (it's an outlined folder)! I'll hopefully have a PR up soon!

((( i also recommend updating the extension logo, which I can also do, with the new vscode logo )))

**Comment by fabiospampinato** [comment]
Cool, thanks. Let's update all the imagery, but I'd prefer to wait for the new VSCode version, which includes the updated icons, to be released first before updating this extension.

**Comment by fabiospampinato** [comment]
I'm writing all the feedback about all the different icons here.

### Activity bar icon

It should be the same icon but with the new style, not an entirely new icon.

Make sure the border width matches exactly to what VSCode is using.

<img width="480" alt="Screen Shot 2019-07-10 at 22 44 35" src="https://user-images.githubusercontent.com/1812093/61003558-89795c80-a364-11e9-8042-c385529b4c9d.png">

### Toolbar icons

Make sure those are copied right from VSCode's source code, as they should look exactly the same as the ones that they are using.

### Extension icon

Just make sure to update the`.psd` too.

**Comment by johnletey** [comment]
@fabiospampinato Will do ... you won't have to merge my PR now ... you can wait until the vscode icons are released!

I will update the activity bar icon later today, I am copying everything directly from the vscode repo so that the extension toolbar icons match, and I'll also edit the extension icon! (btw, what editor do you use to edit a `.psd` file ... i've been using figma for everything design related, but i don't think you can edit `.psd` files)?

Thanks for the feedback!

**Comment by fabiospampinato** [comment]
@johnletey I originally used Photoshop for making that `.psd`, nowadays I've moved to Affinity Photo which _usually_ works of the time for editing pdfs. I'm not familiar with Figma.

**Comment by johnletey** [comment]
I see @fabiospampinato ... I'd prefer to stick with free tools ... I'll see what I can do!

**Comment by fabiospampinato** [comment]
@johnletey It's ok to use another format if you like, as long as I can still open it in Affinity.

**Comment by johnletey** [comment]
Sounds good @fabiospampinato!

**Comment by johnletey** [comment]
@fabiospampinato How does this look for the logo?

![logo](https://user-images.githubusercontent.com/30328854/61167338-0a437e80-a546-11e9-98f0-88515c102d4d.png)

I have also updated all of the icons:

- The activity bar icon is now 24x25 (the exact size as the vscode icons use)
- The rest of the icons are lifted from the vscode source

You can find all of these icons here: [Figma](https://www.figma.com/file/IrU1Nr76NTdIBhv2EMUaRwU7/projects-icons)

I will open a PR if you give the the green light! Also, do you want me to go around the rest of your vscode extensions and update all of the icons in them (I don't mind at all 😄)?

**Comment by fabiospampinato** [comment]
Can you just reuse the same folder icon? I've attached it below.

> Also, do you want me to go around the rest of your vscode extensions and update all of the icons in them (I don't mind at all 😄)?

If you'd like, that'd be useful 👍 

![logo](https://user-images.githubusercontent.com/1812093/61173140-641c6680-a58f-11e9-93d4-443ced53d042.png)

**Comment by johnletey** [comment]
Thanks, @fabiospampinato ... I was looking around for the same background folder image, but couldn't find it 😄

How is this?

![logo](https://user-images.githubusercontent.com/30328854/61178894-26a3f180-a600-11e9-97af-26669a61ec64.png)

Can I go ahead and submit a PR with everything?

**Comment by fabiospampinato** [comment]
Yes it looks good to me 👍

**Comment by johnletey** [comment]
Wonderful ... submitting a PR now!

**Comment by afflexux** [comment]
July update has gone live, look forward to these changes. I use the insiders mostly so kinda got used to the diddy icon! I'll take this opportunity to say thanks for everyone's work on this extension, it's easily in the top 3 of my most used/useful extensions.

**Comment by fabiospampinato** [comment]
Implemented in v1.23.0
