### ISSUE TITLE
Provide an easy way to switch group

### ISSUE THREAD

**Issue by stefano-b** [fabiospampinato/vscode-projects-plus#48]
I think it would be handy to have a quick way to switch the group for the current project.

Let's say that I've set up two groups, `current` and `archived`.

The project that I'm working on is grouped under `current`, and after I complete it, I want to move it in the `archived` group.

Right now, I have to manually open the `.json` file, and cut & paste the project entry from a group to another.

Having the ability to quickly do this from the GUI would be really handy, maybe by adding an option (i.e. `Switch group` or something similar) to the command palette and especially to the right-click menu on the left panel list (the one that currently has `add to workspace`, `open` and `open in new window`)

**Comment by fabiospampinato** [comment]
This sounds like a niche use case, and the more commands we provide the more difficult the whole thing becomes to use.

Actually a more general version of the proposed command is kind of already implemented, just run `Project: Save` and provide a different group when asked. Maybe we should alias "Project: Save" to "Project: Edit" as well?

A separate command just for changing group seems a bit unnecessary to me. A custom context menu action would be interesting, but I don't think we can provide custom submenus, and listing every available group in the main level of the context menu would clutter it too much.

**Comment by fabiospampinato** [comment]
I've added a "Project: Edit" command (which is an alias for "Project: Save") in v1.23.0.
