### ISSUE TITLE
No data provider registered

### ISSUE THREAD

**Issue by rsgranne** [fabiospampinato/vscode-projects-plus#49]
macOS 10.14.6
VSCode: 1.37.0
Latest Projects+

This has been going on for months & months, maybe over a year. I click on the Project button on the Activity Bar, & very often I see this error: "There is no data provider registered that can provide view data."

Often this resolves after a few seconds, but other times it takes a minute, & sometimes, like now, it never resolves until I restart VSCode. 

Hitting the Refresh button may or may not fix the problem.

Not sure what to do at this point.

**Comment by fabiospampinato** [comment]
> This has been going on for months & months, maybe over a year.
> Not sure what to do at this point.

Reporting errors sooner rather than later is generally a good idea.

> very often I see this error: "There is no data provider registered that can provide view data."

Where do you see this error?

> Often this resolves after a few seconds, but other times it takes a minute, & sometimes, like now, it never resolves until I restart VSCode.

I can't actually get any error, can you provide a screenshot or something?

**Comment by rsgranne** [comment]
I see that message where the list of projects should be. 

Next time it happens, I’ll send a screenshot along.
