### ISSUE TITLE
Run an error:Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by hyicy** [fabiospampinato/vscode-projects-plus#50]
When the workspace does not have a folder, the plug-in runs incorrectly : Cannot read property 'uri' of undefined.

vscode: 1.38.1
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362 
projects + : 1.23.0

**Comment by fabiospampinato** [comment]
> When the workspace does not have a folder, the plug-in runs incorrectly : Cannot read property 'uri' of undefined.

I can't reproduce, for me it just works. Did you perhaps misconfigure the extension?

**Comment by hyicy** [comment]
This is my configuration

```json
{
  "projects": [
    {
      "name": "MarkDown",
      "icon": "markdown",
      "description": "",
      "path": "E:\\Seafile\\WorkSpace\\MarkDown"
    }
  ],
  "groups": [
    {
      "name": "RemoteWS",
      "icon": "device-desktop",
      "projects": [
        {
          "name": "main-docker",
          "description": "",
          "path": "e:\\Seafile\\WorkSpace\\RemoteWS\\main-docker.code-workspace"
        },
        {
          "name": "ws-python2",
          "description": "",
          "path": "e:\\Seafile\\WorkSpace\\RemoteWS\\ws-python2.code-workspace"
        }
      ]
    }
  ]
}
```
 `main-docker.code-workspace`, `ws-python2.code-workspace` are remote workspace.

My steps 

1. open a workspace
2. select explorer ,right click on the mouse, select `Remove Rolder from Rorkspace`
3. use `Projects` choose other project, it does not work." Cannot read property 'uri' of undefined"

If the workspace has a folder ,the extension is good.

**Comment by nothatcreative5** [comment]
Facing the same Issue. The extension cannot run the code when there isn't a folder in the workspace and gives the following error in the runtime status:
"Cannot read property 'uri' of undefined."
