### ISSUE TITLE
command 'projects.open' not found

### ISSUE THREAD

**Issue by EdgarVaguencia** [fabiospampinato/vscode-projects-plus#53]
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by zachleigh** [comment]
Same here. This extension doesnt seem to be compatible with the newest version of VSCode.

**Comment by ronggang** [comment]
Me too. And projects list is empty.
![2019-11-08_10-21-41](https://user-images.githubusercontent.com/8065899/68444430-bd309a00-0211-11ea-8f57-1c6b6304fddf.gif)

**Comment by RobinD42** [comment]
The workaround mentioned in #10 works (set the full path to the vscode_projects.json file in the `proejcts.configPath` settings value.)

**Comment by dlampsi** [comment]
Same on:

**Comment by EdgarVaguencia** [comment]
Thanks @RobinD42
