### ISSUE TITLE
indentationSpaces not work

### ISSUE THREAD

**Issue by azchatlanin** [fabiospampinato/vscode-projects-plus#58]
projects.indentationSpaces not work. If change value projects.indentationSpaces = 2 or projects.indentationSpaces = 4 - not effect.

**Comment by fabiospampinato** [comment]
It's working for me, what result did you expect it to make? And instead what are you seeing?

**Comment by azchatlanin** [comment]
If I understand correctly of course

![Screenshot from 2020-01-30 14 51 00](https://user-images.githubusercontent.com/21025345/73447545-02c3b580-4370-11ea-874e-0c5781b8c13f.png)

**Comment by fabiospampinato** [comment]
It changes the indentation in the command palette, no in the sidebar.
