### ISSUE TITLE
refresh erase not parset vcsode_projects.json

### ISSUE THREAD

**Issue by MarekLew** [fabiospampinato/vscode-projects-plus#6]
When I manual editing `vcsode_projects.json` and the file is not parsed as json then after use "Projects: Refresh" then file content is changed to `{}`.

All projects information is lost.

Please do not clean the file if it can not be parsed. Just a parsing error message.

vsc version: 1.15.1
os version: windows 10 Home
extension version: 1.7.2

**Comment by fabiospampinato** [comment]
Thanks for pointing that out. I'm going to fix this with the next update.

Btw I see calling `Projects: Refresh` finds no projects in your system, did you properly set-up the `projects.refreshRoots` setting? Are you using something other than Git or SVN?

**Comment by MarekLew** [comment]
I'm not set `config.refreshRoots` or use gitTower. I`m only convert setting from `Project Manager` extension setting and manual editing is. Then i`m loosing is when added `,` after last element in list and refresh project.    
  
Btw It's confused me the `Projects: Refresh` is in that `Projects: Update`.

**Comment by MarekLew** [comment]
Sory fo my pulllrequest https://github.com/fabiospampinato/vscode-projects-plus/pull/7. It's not tested.

**Comment by bobrocke** [comment]
This bit me, too. I expected 'refresh' to reread the config file because it doesn't appear to happen on file same. Instead it replaced it with a list of my Git projects. That's not bad, it's just not what I wanted, or expected. I must have had a parsing error in the '.json'.

A possible addition would be to reread the config file when it is saved, if you get an event for that.

**Comment by fabiospampinato** [comment]
> Btw It's confused me the Projects: Refresh is in that Projects: Update.

What do you mean? Don't you like the name of the `Projects: Refresh` command?

@MarekLew @bobrocke I'll fix this tomorrow, probably by adding a message that notifies the user about an invalid configuration file and asking if he/she wants the extension to overwrite it or if he/she wants to edit it manually to fix the problem.

**Comment by fabiospampinato** [comment]
@MarekLew @bobrocke It's now fixed.

With the latest version (1.8.1) is possible to write non-strict JSON configurations, basically we can now put comments, trailing commas and unquoted keys in them. All this things will get eventually removed as soon as a `Projects: Refresh` or a `Project: Save` is run, but they won't cause any error when reading the file.

In case the configuration is still considered improperly formatted, an error message will be shown, asking if you want to overwrite it or edit it manually. It won't get silently overwritten.
