### ISSUE TITLE
Proposed API error with latest Insiders

### ISSUE THREAD

**Issue by manastalukdar** [fabiospampinato/vscode-projects-plus#67]
Projects do not load.

```
[fabiospampinato.vscode-projects-plus]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api fabiospampinato.vscode-projects-plus
```

Version: 1.50.0-insider (user setup)
Commit: bc38b0accb3c62180317c63dbe7323200977db0f
Date: 2020-09-11T12:48:20.764Z (12 hrs ago)
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by fabiospampinato** [comment]
🤔 I'm not sure what this is about exactly, I don't have time to support Insider too, let's wait until stable breaks, unless somebody would like to submit a PR.

**Comment by manastalukdar** [comment]
This got fixed with the next Insiders build. Closing.
