### ISSUE TITLE
Purpose of the extension is not stated clearly

### ISSUE THREAD

**Issue by JOJ0** [fabiospampinato/vscode-projects-plus#70]
Hi, thanks for, I am sure, a very helpful extension for some people.

I just wanted to mention that I am trying to figure out what kind of "projects" this extension is helping me with. Is it an integration of github projects? Or projects of another external resource? Or it's own projects format?

I suggest clarifying what exactley "projects" means and what the purpose of the extension is would help understand people more quickly if the extension is for them or not. 

Thanks for considering improving the first parts of your extensions help text / github readme.
Hope that helps
Jojo

**Comment by 4lch4** [comment]
Hey @JOJ0, I'm not part of the folks that built the extension but "Projects" to me isn't tied to any other service or tech really. Instead, a Project is just a collection of folders and/or files.

For example, if you have a website like [StrawPoll][0] you'd likely have a directory that's the front end service/app, and another for the web service that handles backend requests.

The Project in this case would be the entirety of the StrawPoll website, and it would consist of the FE app as well as the BE web service.

That said, I do get where you're coming from and agree it'd be helpful. Judging by the lack of reply to your Issue though, I'd imagine @fabiospampinato has shifted focus towards other projects.

Personally, if this question/issue remains unanswered then I'll create a fork of the repo and see what I can do to address the outstanding Issues/PRs.

[0]: https://www.strawpoll.me/

**Comment by JOJ0** [comment]
Hi @4lch4, thanks for taking the time to explain what it's all about! Sounds useful, I don't use the extension currently though. Right, this repo seems quite abandoned atm. Good luck with the fork! I'll keep watching this issue and I might have a use for the extension in the future.

**Comment by fabiospampinato** [comment]
Yeah I'm pretty busy with other projects at the moment, and the little fundraiser thing didn't work out nearly as well as I had hoped. @4lch4 Have you forked the extension already.
