### ISSUE TITLE
Folder icon or color per project

### ISSUE THREAD

**Issue by act360web** [fabiospampinato/vscode-projects-plus#73]
It would be very efficient if we can distinguish the group projects per folder color or icon.
 
Case scenario: We have multiple groups with quite a few projects in it (Git branches). We need to identify if the project status is currently active, pending review, ready to launch, launched, pending for deletion, and so on.

Maybe a feature to pick the folder color or icon would be enough but also adding a description would be great.

**Comment by fabiospampinato** [comment]
This extension already supports icons, read the bottom of the readme.

I don't think vscode supports coloring icons and texts differently though, so that can't be implemented.
