### ISSUE TITLE
Errors in configuration?

### ISSUE THREAD

**Issue by bobrocke** [fabiospampinato/vscode-projects-plus#8]
Projects+ appears to not like my configuration file. I get a blank Projects pane in the Explorer and a fresh, default, configuration if I refresh the project list. VSCode shows no syntax errors from its JSON linter. What have I missed?

```
{
  "groups": [
    {
      "name": "Group", // Group's name
      "projects": [
        {
          "name": "www.br.dev",
          "path": "/Users/bob/Sites/www.br.dev"
        }
      ]
    }
  ],
  "projects": [
    {
      "name": "topicmenu",
      "path": "/Users/bob/Documents/Web%20Development/Projects/topicmenu"
    },
    {
      "name": "topicmenu",
      "path": "/Users/bob/Documents/Web%20Development/Projects/topicmenu"
    },
    {
      "name": "www.materialize.dev",
      "path": "/Users/bob/Sites/www.materialize.dev"
    },
    {
      "name": "www.br.dev",
      "path": "/Users/bob/Sites/www.br.dev"
    },
    {
      "name": "materialize",
      "path": "/Users/bob/Documents/Web%20Development/Projects/materialize"
    },
    {
      "name": "materializer",
      "path": "/Users/bob/Documents/Web%20Development/Projects/materializer"
    },
    {
      "name": "Solar Light",
      "path": "/Users/bob/Documents/Development/Text%20Colors/Espresso/Solar%20Light"
    }
  ]
}
```

**Comment by fabiospampinato** [comment]
Comments are not allowed by the [JSON](http://json.org) specification. you should remove that `// Group's name` string.

Visual Studio Code ignores that, but the extension doesn't.  There's an issue (https://github.com/Microsoft/vscode/issues/3641) about that in VSC's repository.

I'll investigate the use of a different function for parsing this configuration that supports comments.

**Comment by bobrocke** [comment]
Thanks for the quick response. Removing the comments fixed it; I had copied the example configuration from the docs.

But.

Something I've done is still not right. This configuration:

```
{
  "groups": [
    {
      "name": "www.br.dev",
      "projects": [
        {
          "name": "All Files",
          "path": "/Users/bob/Sites/www.br.dev"
        },
        {
          "name": "Pages",
          "path": "/Users/bob/Sites/www.br.dev/user/pages"
        }
      ]
    }
  ],
  "projects": [
    {
      "name": "topicmenu",
      "path": "/Users/bob/Documents/Web%20Development/Projects/topicmenu"
    },
    {
      "name": "topicmenu",
      "path": "/Users/bob/Documents/Web%20Development/Projects/topicmenu"
    },
    {
      "name": "www.materialize.dev",
      "path": "/Users/bob/Sites/www.materialize.dev"
    },
    {
      "name": "materialize",
      "path": "/Users/bob/Documents/Web%20Development/Projects/materialize"
    },
    {
      "name": "materializer",
      "path": "/Users/bob/Documents/Web%20Development/Projects/materializer"
    },
    {
      "name": "Solar Light",
      "path": "/Users/bob/Documents/Development/Text%20Colors/Espresso/Solar%20Light"
    }
  ]
}
```

Get me this Project Pane:

![2017-08-26 at 8 59 am](https://user-images.githubusercontent.com/2962426/29741522-e407b52c-8a3c-11e7-96f8-6781e008c90a.jpg)

No groups!

**Comment by fabiospampinato** [comment]
I can't reproduce it.

Do you basically get the same problem when opening Projects+'s quick projects switcher? (click the statusbar item to trigger it, or do a Alt+Cmd+P)

If you changed any of Projects+'s global settings, can you paste them here?

What is the opened folder in the VSC instance that shows the problem?

What version of VSC are you running?

**Comment by bobrocke** [comment]
I do have the same problem in the quick switcher:

![2017-08-26 at 9 34 am](https://user-images.githubusercontent.com/2962426/29741817-d8fe262a-8a41-11e7-8850-c1726c32285a.jpg)

If by global setting your mean the same as VSC preferences, this is the only change:

```
   "projects.configPath": "/Users/bob/Sites/vscode_projects.json"
```

The opened folder is `/Users/bob/Sites/www.br.dev`.

And it's VSC v1.15.1.

Thanks for the help!

**Comment by fabiospampinato** [comment]
I still can't reproduce it.

Try to update the extension to v1.8.1.

If the problem persists try to start with a very simple configuration, perhaps just a single project or group, and build up from that incrementally until things break, then paste me the latest working configuration and the one right after that (which causes the problem).

**Comment by bobrocke** [comment]
Found it, fixed it!

I had: `"projects.configPath": "/Users/bob/Sites/vscode_projects.json"`

Should be: `"projects.configPath": "/Users/bob/Sites/.vscode_projects.json"`

Missed the leading `.` in the filename! Duh!

**Comment by fabiospampinato** [comment]
I'm glad you found the issue :)
